"""
Workflow plan schema with strict validation.

Defines the structure of workflow plans generated by the planner,
including versioning, confidence metadata, and validation rules.
"""

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field, field_validator


class PlanVersion(str, Enum):
    """Supported plan schema versions."""

    V1 = "1.0"


class TaskDependencyType(str, Enum):
    """Types of task dependencies."""

    SEQUENTIAL = "sequential"  # Must complete before dependent starts
    PARALLEL = "parallel"  # Can run simultaneously
    CONDITIONAL = "conditional"  # Depends on outcome of another task


class WorkflowPlanTask(BaseModel):
    """Individual task in a workflow plan."""

    id: str = Field(..., min_length=1, max_length=100, description="Unique task identifier")
    agent: str = Field(..., min_length=1, max_length=100, description="Agent responsible for task")
    title: str = Field(..., min_length=1, max_length=500, description="Short task title")
    description: str = Field(..., min_length=1, max_length=2000, description="Detailed task description")
    depends_on: List[str] = Field(default_factory=list, description="Task IDs this task depends on")
    optional: bool = Field(default=False, description="Whether task can be skipped on failure")
    timeout_seconds: int = Field(default=300, ge=10, le=3600, description="Max execution time")
    retry_count: int = Field(default=1, ge=1, le=5, description="Max retry attempts")

    @field_validator("depends_on")
    @classmethod
    def validate_no_self_dependency(cls, v: List[str], info):
        """Ensure task doesn't depend on itself."""
        if info.data.get("id") and info.data["id"] in v:
            raise ValueError(f"Task cannot depend on itself: {info.data['id']}")
        return v


class WorkflowPlan(BaseModel):
    """Complete workflow plan with validation metadata."""

    version: str = PlanVersion.V1
    tasks: List[WorkflowPlanTask] = Field(..., min_length=1, max_length=50, description="List of tasks")
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0, description="Planner confidence (0-1)")
    max_parallel_depth: int = Field(
        default=2, ge=1, le=10, description="Maximum depth of parallel task levels"
    )
    estimated_duration_seconds: int = Field(
        default=600, ge=10, le=7200, description="Estimated total execution time"
    )
    mode: str = Field(..., description="Workflow mode (chat, rag, workflow)")
    error_category: Optional[str] = Field(default=None, description="Error category if plan is invalid")
    validation_warnings: List[str] = Field(default_factory=list, description="Non-fatal validation issues")
    fallback_used: bool = Field(default=False, description="Whether this is a fallback plan")

    @field_validator("tasks")
    @classmethod
    def validate_unique_task_ids(cls, v: List[WorkflowPlanTask]):
        """Ensure all task IDs are unique."""
        ids = [t.id for t in v]
        if len(ids) != len(set(ids)):
            duplicates = [id for id in ids if ids.count(id) > 1]
            raise ValueError(f"Duplicate task IDs: {duplicates}")
        return v

    @field_validator("tasks")
    @classmethod
    def validate_referenced_dependencies(cls, v: List[WorkflowPlanTask]):
        """Ensure all referenced task dependencies exist."""
        task_ids = {t.id for t in v}
        for task in v:
            for dep in task.depends_on:
                if dep not in task_ids:
                    raise ValueError(f"Task {task.id} depends on non-existent task: {dep}")
        return v


class PlanLintError(BaseModel):
    """Linter error with error code and severity."""

    code: str = Field(..., description="Error code (e.g., CYCLE_DETECTED, MAX_FANOUT_EXCEEDED)")
    severity: str = Field(..., description="Severity: error or warning")
    message: str = Field(..., description="Human-readable error message")
    task_ids: List[str] = Field(default_factory=list, description="Task IDs involved in error")
    details: Dict[str, str] = Field(default_factory=dict, description="Additional details")


class PlanLintResult(BaseModel):
    """Result of plan linting."""

    is_valid: bool = Field(..., description="Whether plan passed all validations")
    errors: List[PlanLintError] = Field(default_factory=list, description="Critical errors")
    warnings: List[PlanLintError] = Field(default_factory=list, description="Non-blocking warnings")
    metrics: Dict[str, int] = Field(
        default_factory=dict,
        description="Plan metrics (task_count, max_depth, max_fanout, cycle_count)",
    )


class FallbackPlan(BaseModel):
    """Fallback plan (hardcoded safe plan) for recovery."""

    mode: str = Field(..., description="Workflow mode this fallback is for")
    plan: WorkflowPlan = Field(..., description="Fallback plan definition")
    reason: str = Field(..., description="Why this fallback exists")
